/**
 * Generated by packages/db/scripts/generate-types.mjs — do not edit by hand.
 *
 * Regenerate after any schema migration:
 *   su postgres -c 'PGTEST_DIR=/tmp/aec-pgtest bash tests/sql/run.sh --keep-running'
 *   node packages/db/scripts/generate-types.mjs "$DATABASE_URL"
 *
 * (or point it at any Postgres that already has every migration applied —
 * a local `supabase start`, or the disposable instance tests/sql/run.sh
 * builds.)
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      attachments: {
        Row: {
          id: string;
          company_id: string;
          transaction_id: string;
          storage_path: string;
          file_name: string;
          content_type: string | null;
          size_bytes: number | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          transaction_id: string;
          storage_path: string;
          file_name: string;
          content_type?: string | null;
          size_bytes?: number | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          transaction_id?: string;
          storage_path?: string;
          file_name?: string;
          content_type?: string | null;
          size_bytes?: number | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: number;
          company_id: string | null;
          table_name: string;
          row_id: string | null;
          action: string;
          old_data: Json | null;
          new_data: Json | null;
          changed_by: string | null;
          changed_at: string;
        };
        Insert: {
          id?: number;
          company_id?: string | null;
          table_name: string;
          row_id?: string | null;
          action: string;
          old_data?: Json | null;
          new_data?: Json | null;
          changed_by?: string | null;
          changed_at?: string;
        };
        Update: {
          id?: number;
          company_id?: string | null;
          table_name?: string;
          row_id?: string | null;
          action?: string;
          old_data?: Json | null;
          new_data?: Json | null;
          changed_by?: string | null;
          changed_at?: string;
        };
        Relationships: [];
      };
      bank_accounts: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          kind: "corrente" | "poupanca" | "aplicacao" | "cartao_credito" | "caixa";
          bank_code: string | null;
          bank_name: string | null;
          branch: string | null;
          account_number: string | null;
          opening_balance: string;
          opening_balance_date: string;
          minimum_balance: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          kind?: "corrente" | "poupanca" | "aplicacao" | "cartao_credito" | "caixa";
          bank_code?: string | null;
          bank_name?: string | null;
          branch?: string | null;
          account_number?: string | null;
          opening_balance?: string;
          opening_balance_date: string;
          minimum_balance?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          kind?: "corrente" | "poupanca" | "aplicacao" | "cartao_credito" | "caixa";
          bank_code?: string | null;
          bank_name?: string | null;
          branch?: string | null;
          account_number?: string | null;
          opening_balance?: string;
          opening_balance_date?: string;
          minimum_balance?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          company_id: string;
          parent_id: string | null;
          name: string;
          kind: "entrada" | "saida" | "ambos";
          ledger_account: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          parent_id?: string | null;
          name: string;
          kind: "entrada" | "saida" | "ambos";
          ledger_account?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          parent_id?: string | null;
          name?: string;
          kind?: "entrada" | "saida" | "ambos";
          ledger_account?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      companies: {
        Row: {
          id: string;
          name: string;
          legal_name: string | null;
          tax_id: string | null;
          timezone: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          legal_name?: string | null;
          tax_id?: string | null;
          timezone?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          legal_name?: string | null;
          tax_id?: string | null;
          timezone?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cost_centers: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      counterparties: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          tax_id: string | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          tax_id?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          tax_id?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      matching_rules: {
        Row: {
          id: string;
          company_id: string;
          match_text: string;
          bank_account_id: string | null;
          direction: "entrada" | "saida" | null;
          category_id: string | null;
          counterparty_id: string | null;
          cost_center_id: string | null;
          priority: number;
          hit_count: number;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          match_text: string;
          bank_account_id?: string | null;
          direction?: "entrada" | "saida" | null;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          priority?: number;
          hit_count?: number;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          match_text?: string;
          bank_account_id?: string | null;
          direction?: "entrada" | "saida" | null;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          priority?: number;
          hit_count?: number;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      memberships: {
        Row: {
          id: string;
          company_id: string;
          user_id: string;
          role: "cliente_leitura" | "assistente" | "contador" | "owner";
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          user_id: string;
          role?: "cliente_leitura" | "assistente" | "contador" | "owner";
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          user_id?: string;
          role?: "cliente_leitura" | "assistente" | "contador" | "owner";
          created_at?: string;
        };
        Relationships: [];
      };
      monthly_closing_balances: {
        Row: {
          closing_id: string;
          bank_account_id: string;
          closing_balance: string;
        };
        Insert: {
          closing_id: string;
          bank_account_id: string;
          closing_balance: string;
        };
        Update: {
          closing_id?: string;
          bank_account_id?: string;
          closing_balance?: string;
        };
        Relationships: [];
      };
      monthly_closings: {
        Row: {
          id: string;
          company_id: string;
          period: string;
          locked_at: string | null;
          locked_by: string | null;
          reopened_at: string | null;
          reopened_by: string | null;
          reopen_reason: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          period: string;
          locked_at?: string | null;
          locked_by?: string | null;
          reopened_at?: string | null;
          reopened_by?: string | null;
          reopen_reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          period?: string;
          locked_at?: string | null;
          locked_by?: string | null;
          reopened_at?: string | null;
          reopened_by?: string | null;
          reopen_reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      recurrences: {
        Row: {
          id: string;
          company_id: string;
          bank_account_id: string;
          category_id: string | null;
          counterparty_id: string | null;
          cost_center_id: string | null;
          description: string;
          amount: string;
          frequency: "mensal" | "semanal" | "quinzenal" | "anual";
          day_of_month: number | null;
          start_date: string;
          end_date: string | null;
          generated_until: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          bank_account_id: string;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          description: string;
          amount: string;
          frequency?: "mensal" | "semanal" | "quinzenal" | "anual";
          day_of_month?: number | null;
          start_date: string;
          end_date?: string | null;
          generated_until?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          bank_account_id?: string;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          description?: string;
          amount?: string;
          frequency?: "mensal" | "semanal" | "quinzenal" | "anual";
          day_of_month?: number | null;
          start_date?: string;
          end_date?: string | null;
          generated_until?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      statement_imports: {
        Row: {
          id: string;
          company_id: string;
          bank_account_id: string;
          source: "ofx" | "csv" | "manual" | "open_finance" | "pdf";
          file_name: string | null;
          file_hash: string | null;
          period_start: string | null;
          period_end: string | null;
          statement_balance: string | null;
          statement_balance_date: string | null;
          line_count: number;
          imported_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          bank_account_id: string;
          source: "ofx" | "csv" | "manual" | "open_finance" | "pdf";
          file_name?: string | null;
          file_hash?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          statement_balance?: string | null;
          statement_balance_date?: string | null;
          line_count?: number;
          imported_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          bank_account_id?: string;
          source?: "ofx" | "csv" | "manual" | "open_finance" | "pdf";
          file_name?: string | null;
          file_hash?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          statement_balance?: string | null;
          statement_balance_date?: string | null;
          line_count?: number;
          imported_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      statement_lines: {
        Row: {
          id: string;
          company_id: string;
          import_id: string;
          bank_account_id: string;
          posted_at: string;
          amount: string;
          memo: string;
          fitid: string | null;
          dedup_key: string;
          status: "pendente" | "conciliada" | "criada" | "ignorada";
          matched_transaction_id: string | null;
          matched_at: string | null;
          matched_by: string | null;
          created_at: string;
          ignored_reason: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          import_id: string;
          bank_account_id: string;
          posted_at: string;
          amount: string;
          memo?: string;
          fitid?: string | null;
          dedup_key: string;
          status?: "pendente" | "conciliada" | "criada" | "ignorada";
          matched_transaction_id?: string | null;
          matched_at?: string | null;
          matched_by?: string | null;
          created_at?: string;
          ignored_reason?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          import_id?: string;
          bank_account_id?: string;
          posted_at?: string;
          amount?: string;
          memo?: string;
          fitid?: string | null;
          dedup_key?: string;
          status?: "pendente" | "conciliada" | "criada" | "ignorada";
          matched_transaction_id?: string | null;
          matched_at?: string | null;
          matched_by?: string | null;
          created_at?: string;
          ignored_reason?: string | null;
        };
        Relationships: [];
      };
      transactions: {
        Row: {
          id: string;
          company_id: string;
          bank_account_id: string;
          category_id: string | null;
          counterparty_id: string | null;
          cost_center_id: string | null;
          booking_date: string;
          competence_date: string;
          amount: string;
          direction: "entrada" | "saida" | null;
          status: "previsto" | "realizado";
          reconciliation: "nao_conciliado" | "conciliado" | "ignorado";
          payment_method:
            | "pix"
            | "ted"
            | "doc"
            | "boleto"
            | "debito_automatico"
            | "cartao"
            | "dinheiro"
            | "cheque"
            | "outro"
            | null;
          description: string;
          document_number: string | null;
          notes: string | null;
          transfer_group_id: string | null;
          is_transfer: boolean | null;
          recurrence_id: string | null;
          settles_transaction_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          bank_account_id: string;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          booking_date: string;
          competence_date: string;
          amount: string;
          status?: "previsto" | "realizado";
          reconciliation?: "nao_conciliado" | "conciliado" | "ignorado";
          payment_method?:
            | "pix"
            | "ted"
            | "doc"
            | "boleto"
            | "debito_automatico"
            | "cartao"
            | "dinheiro"
            | "cheque"
            | "outro"
            | null;
          description: string;
          document_number?: string | null;
          notes?: string | null;
          transfer_group_id?: string | null;
          recurrence_id?: string | null;
          settles_transaction_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          bank_account_id?: string;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          booking_date?: string;
          competence_date?: string;
          amount?: string;
          status?: "previsto" | "realizado";
          reconciliation?: "nao_conciliado" | "conciliado" | "ignorado";
          payment_method?:
            | "pix"
            | "ted"
            | "doc"
            | "boleto"
            | "debito_automatico"
            | "cartao"
            | "dinheiro"
            | "cheque"
            | "outro"
            | null;
          description?: string;
          document_number?: string | null;
          notes?: string | null;
          transfer_group_id?: string | null;
          recurrence_id?: string | null;
          settles_transaction_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      v_account_balances: {
        Row: {
          bank_account_id: string | null;
          company_id: string | null;
          name: string | null;
          kind: "corrente" | "poupanca" | "aplicacao" | "cartao_credito" | "caixa" | null;
          bank_name: string | null;
          is_active: boolean | null;
          opening_balance: string | null;
          opening_balance_date: string | null;
          minimum_balance: string | null;
          current_balance: string | null;
          realized_balance: string | null;
          projected_balance: string | null;
          overdue_amount: string | null;
          unreconciled_count: number | null;
        };
        Relationships: [];
      };
      v_account_daily_movement: {
        Row: {
          company_id: string | null;
          bank_account_id: string | null;
          booking_date: string | null;
          status: "previsto" | "realizado" | null;
          net_amount: string | null;
          inflow: string | null;
          outflow: string | null;
          entry_count: number | null;
        };
        Relationships: [];
      };
      v_monthly_category_summary: {
        Row: {
          company_id: string | null;
          period_cash: string | null;
          period_accrual: string | null;
          category_id: string | null;
          category_name: string | null;
          direction: "entrada" | "saida" | null;
          status: "previsto" | "realizado" | null;
          total_amount: string | null;
          entry_count: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      close_month: {
        Args: { p_company_id: string; p_period: string; p_notes?: string | null };
        Returns: Database["public"]["Tables"]["monthly_closings"]["Row"];
      };
      create_company: {
        Args: { p_name: string; p_legal_name?: string | null; p_tax_id?: string | null };
        Returns: Database["public"]["Tables"]["companies"]["Row"];
      };
      create_transaction_from_line: {
        Args: { p_line_id: string; p_category_id?: string | null; p_description?: string | null };
        Returns: Database["public"]["Tables"]["transactions"]["Row"];
      };
      create_transfer: {
        Args: {
          p_company_id: string;
          p_from_account_id: string;
          p_to_account_id: string;
          p_amount: string;
          p_booking_date: string;
          p_description: string;
          p_notes?: string | null;
        };
        Returns: string;
      };
      ignore_line: {
        Args: { p_line_id: string; p_reason: string };
        Returns: undefined;
      };
      reconcile_line: {
        Args: { p_line_id: string; p_transaction_id: string };
        Returns: undefined;
      };
      reopen_month: {
        Args: { p_company_id: string; p_period: string; p_reason: string };
        Returns: Database["public"]["Tables"]["monthly_closings"]["Row"];
      };
      settle_transaction: {
        Args: {
          p_transaction_id: string;
          p_booking_date?: string | null;
          p_amount?: string | null;
        };
        Returns: Database["public"]["Tables"]["transactions"]["Row"];
      };
      unreconcile_line: {
        Args: { p_line_id: string };
        Returns: undefined;
      };
    };
    Enums: {
      bank_account_kind: "corrente" | "poupanca" | "aplicacao" | "cartao_credito" | "caixa";
      category_kind: "entrada" | "saida" | "ambos";
      member_role: "cliente_leitura" | "assistente" | "contador" | "owner";
      payment_method:
        | "pix"
        | "ted"
        | "doc"
        | "boleto"
        | "debito_automatico"
        | "cartao"
        | "dinheiro"
        | "cheque"
        | "outro";
      reconciliation_status: "nao_conciliado" | "conciliado" | "ignorado";
      recurrence_frequency: "mensal" | "semanal" | "quinzenal" | "anual";
      statement_line_status: "pendente" | "conciliada" | "criada" | "ignorada";
      statement_source: "ofx" | "csv" | "manual" | "open_finance" | "pdf";
      transaction_direction: "entrada" | "saida";
      transaction_status: "previsto" | "realizado";
    };
  };
}
