/**
 * Generated by packages/db/scripts/generate-types.mjs — do not edit by hand.
 *
 * Regenerate after any schema migration:
 *   su postgres -c 'bash packages/db/scripts/dev-db.sh'   # prints a connection string
 *   node packages/db/scripts/generate-types.mjs "$DATABASE_URL"
 *   pnpm exec prettier --write packages/db/src/database.types.ts
 *
 * (or point it at any Postgres that already has every migration applied —
 * a local `supabase start` works too. dev-db.sh exists instead of
 * tests/sql/run.sh here because that script tears its instance down the
 * moment it finishes, which is right for a test run and useless for this.)
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      attachments: {
        Row: {
          id: string;
          company_id: string;
          transaction_id: string;
          storage_path: string;
          file_name: string;
          content_type: string | null;
          size_bytes: number | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          transaction_id: string;
          storage_path: string;
          file_name: string;
          content_type?: string | null;
          size_bytes?: number | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          transaction_id?: string;
          storage_path?: string;
          file_name?: string;
          content_type?: string | null;
          size_bytes?: number | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "attachments_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "attachments_transaction_id_fkey";
            columns: ["transaction_id"];
            isOneToOne: false;
            referencedRelation: "transactions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "attachments_uploaded_by_fkey";
            columns: ["uploaded_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_log: {
        Row: {
          id: number;
          company_id: string | null;
          table_name: string;
          row_id: string | null;
          action: string;
          old_data: Json | null;
          new_data: Json | null;
          changed_by: string | null;
          changed_at: string;
        };
        Insert: {
          id?: number;
          company_id?: string | null;
          table_name: string;
          row_id?: string | null;
          action: string;
          old_data?: Json | null;
          new_data?: Json | null;
          changed_by?: string | null;
          changed_at?: string;
        };
        Update: {
          id?: number;
          company_id?: string | null;
          table_name?: string;
          row_id?: string | null;
          action?: string;
          old_data?: Json | null;
          new_data?: Json | null;
          changed_by?: string | null;
          changed_at?: string;
        };
        Relationships: [];
      };
      bank_accounts: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          kind: "corrente" | "poupanca" | "aplicacao" | "cartao_credito" | "caixa";
          bank_code: string | null;
          bank_name: string | null;
          branch: string | null;
          account_number: string | null;
          opening_balance: string;
          opening_balance_date: string;
          minimum_balance: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          kind?: "corrente" | "poupanca" | "aplicacao" | "cartao_credito" | "caixa";
          bank_code?: string | null;
          bank_name?: string | null;
          branch?: string | null;
          account_number?: string | null;
          opening_balance?: string;
          opening_balance_date: string;
          minimum_balance?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          kind?: "corrente" | "poupanca" | "aplicacao" | "cartao_credito" | "caixa";
          bank_code?: string | null;
          bank_name?: string | null;
          branch?: string | null;
          account_number?: string | null;
          opening_balance?: string;
          opening_balance_date?: string;
          minimum_balance?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "bank_accounts_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };
      categories: {
        Row: {
          id: string;
          company_id: string;
          parent_id: string | null;
          name: string;
          kind: "entrada" | "saida" | "ambos";
          ledger_account: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          parent_id?: string | null;
          name: string;
          kind: "entrada" | "saida" | "ambos";
          ledger_account?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          parent_id?: string | null;
          name?: string;
          kind?: "entrada" | "saida" | "ambos";
          ledger_account?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "categories_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "categories_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
        ];
      };
      companies: {
        Row: {
          id: string;
          name: string;
          legal_name: string | null;
          tax_id: string | null;
          timezone: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          legal_name?: string | null;
          tax_id?: string | null;
          timezone?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          legal_name?: string | null;
          tax_id?: string | null;
          timezone?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cost_centers: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "cost_centers_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };
      counterparties: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          tax_id: string | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          tax_id?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          tax_id?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "counterparties_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };
      invoice_settlements: {
        Row: {
          id: string;
          company_id: string;
          invoice_id: string;
          transaction_id: string;
          amount: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          invoice_id: string;
          transaction_id: string;
          amount: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          invoice_id?: string;
          transaction_id?: string;
          amount?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "invoice_settlements_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoice_settlements_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoice_settlements_invoice_fk";
            columns: ["invoice_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "invoices";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "invoice_settlements_transaction_id_fkey";
            columns: ["transaction_id"];
            isOneToOne: false;
            referencedRelation: "transactions";
            referencedColumns: ["id"];
          },
        ];
      };
      invoices: {
        Row: {
          id: string;
          company_id: string;
          number: string;
          series: string | null;
          verification_code: string | null;
          issued_on: string;
          due_on: string | null;
          amount: string;
          withheld_amount: string;
          counterparty_id: string | null;
          client_name: string;
          client_tax_id: string | null;
          status: "aberta" | "recebida_parcial" | "recebida" | "cancelada";
          source_file_name: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          number: string;
          series?: string | null;
          verification_code?: string | null;
          issued_on: string;
          due_on?: string | null;
          amount: string;
          withheld_amount?: string;
          counterparty_id?: string | null;
          client_name: string;
          client_tax_id?: string | null;
          status?: "aberta" | "recebida_parcial" | "recebida" | "cancelada";
          source_file_name?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          number?: string;
          series?: string | null;
          verification_code?: string | null;
          issued_on?: string;
          due_on?: string | null;
          amount?: string;
          withheld_amount?: string;
          counterparty_id?: string | null;
          client_name?: string;
          client_tax_id?: string | null;
          status?: "aberta" | "recebida_parcial" | "recebida" | "cancelada";
          source_file_name?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "invoices_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoices_counterparty_fk";
            columns: ["counterparty_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "counterparties";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "invoices_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      matching_rules: {
        Row: {
          id: string;
          company_id: string;
          match_text: string;
          bank_account_id: string | null;
          direction: "entrada" | "saida" | null;
          category_id: string | null;
          counterparty_id: string | null;
          cost_center_id: string | null;
          priority: number;
          hit_count: number;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          match_text: string;
          bank_account_id?: string | null;
          direction?: "entrada" | "saida" | null;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          priority?: number;
          hit_count?: number;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          match_text?: string;
          bank_account_id?: string | null;
          direction?: "entrada" | "saida" | null;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          priority?: number;
          hit_count?: number;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "matching_rules_bank_account_fk";
            columns: ["bank_account_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "bank_accounts";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "matching_rules_category_fk";
            columns: ["category_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "matching_rules_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "matching_rules_cost_center_fk";
            columns: ["cost_center_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "cost_centers";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "matching_rules_counterparty_fk";
            columns: ["counterparty_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "counterparties";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "matching_rules_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      memberships: {
        Row: {
          id: string;
          company_id: string;
          user_id: string;
          role: "cliente_leitura" | "assistente" | "contador" | "owner";
          created_at: string;
          simple_mode: boolean;
        };
        Insert: {
          id?: string;
          company_id: string;
          user_id: string;
          role?: "cliente_leitura" | "assistente" | "contador" | "owner";
          created_at?: string;
          simple_mode?: boolean;
        };
        Update: {
          id?: string;
          company_id?: string;
          user_id?: string;
          role?: "cliente_leitura" | "assistente" | "contador" | "owner";
          created_at?: string;
          simple_mode?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "memberships_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "memberships_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      monthly_closing_balances: {
        Row: {
          closing_id: string;
          bank_account_id: string;
          closing_balance: string;
        };
        Insert: {
          closing_id: string;
          bank_account_id: string;
          closing_balance: string;
        };
        Update: {
          closing_id?: string;
          bank_account_id?: string;
          closing_balance?: string;
        };
        Relationships: [
          {
            foreignKeyName: "monthly_closing_balances_bank_account_id_fkey";
            columns: ["bank_account_id"];
            isOneToOne: false;
            referencedRelation: "bank_accounts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "monthly_closing_balances_closing_id_fkey";
            columns: ["closing_id"];
            isOneToOne: false;
            referencedRelation: "monthly_closings";
            referencedColumns: ["id"];
          },
        ];
      };
      monthly_closings: {
        Row: {
          id: string;
          company_id: string;
          period: string;
          locked_at: string | null;
          locked_by: string | null;
          reopened_at: string | null;
          reopened_by: string | null;
          reopen_reason: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          period: string;
          locked_at?: string | null;
          locked_by?: string | null;
          reopened_at?: string | null;
          reopened_by?: string | null;
          reopen_reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          period?: string;
          locked_at?: string | null;
          locked_by?: string | null;
          reopened_at?: string | null;
          reopened_by?: string | null;
          reopen_reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "monthly_closings_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "monthly_closings_locked_by_fkey";
            columns: ["locked_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "monthly_closings_reopened_by_fkey";
            columns: ["reopened_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      recurrences: {
        Row: {
          id: string;
          company_id: string;
          bank_account_id: string;
          category_id: string | null;
          counterparty_id: string | null;
          cost_center_id: string | null;
          description: string;
          amount: string;
          frequency: "mensal" | "semanal" | "quinzenal" | "anual";
          day_of_month: number | null;
          start_date: string;
          end_date: string | null;
          generated_until: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          bank_account_id: string;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          description: string;
          amount: string;
          frequency?: "mensal" | "semanal" | "quinzenal" | "anual";
          day_of_month?: number | null;
          start_date: string;
          end_date?: string | null;
          generated_until?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          bank_account_id?: string;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          description?: string;
          amount?: string;
          frequency?: "mensal" | "semanal" | "quinzenal" | "anual";
          day_of_month?: number | null;
          start_date?: string;
          end_date?: string | null;
          generated_until?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recurrences_bank_account_fk";
            columns: ["bank_account_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "bank_accounts";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "recurrences_category_fk";
            columns: ["category_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "recurrences_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recurrences_cost_center_fk";
            columns: ["cost_center_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "cost_centers";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "recurrences_counterparty_fk";
            columns: ["counterparty_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "counterparties";
            referencedColumns: ["id", "company_id"];
          },
        ];
      };
      statement_imports: {
        Row: {
          id: string;
          company_id: string;
          bank_account_id: string;
          source: "ofx" | "csv" | "manual" | "open_finance" | "pdf";
          file_name: string | null;
          file_hash: string | null;
          period_start: string | null;
          period_end: string | null;
          statement_balance: string | null;
          statement_balance_date: string | null;
          line_count: number;
          imported_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          bank_account_id: string;
          source: "ofx" | "csv" | "manual" | "open_finance" | "pdf";
          file_name?: string | null;
          file_hash?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          statement_balance?: string | null;
          statement_balance_date?: string | null;
          line_count?: number;
          imported_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          bank_account_id?: string;
          source?: "ofx" | "csv" | "manual" | "open_finance" | "pdf";
          file_name?: string | null;
          file_hash?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          statement_balance?: string | null;
          statement_balance_date?: string | null;
          line_count?: number;
          imported_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "statement_imports_bank_account_fk";
            columns: ["bank_account_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "bank_accounts";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "statement_imports_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "statement_imports_imported_by_fkey";
            columns: ["imported_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      statement_lines: {
        Row: {
          id: string;
          company_id: string;
          import_id: string;
          bank_account_id: string;
          posted_at: string;
          amount: string;
          memo: string;
          fitid: string | null;
          dedup_key: string;
          status: "pendente" | "conciliada" | "criada" | "ignorada";
          matched_transaction_id: string | null;
          matched_at: string | null;
          matched_by: string | null;
          created_at: string;
          ignored_reason: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          import_id: string;
          bank_account_id: string;
          posted_at: string;
          amount: string;
          memo?: string;
          fitid?: string | null;
          dedup_key: string;
          status?: "pendente" | "conciliada" | "criada" | "ignorada";
          matched_transaction_id?: string | null;
          matched_at?: string | null;
          matched_by?: string | null;
          created_at?: string;
          ignored_reason?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          import_id?: string;
          bank_account_id?: string;
          posted_at?: string;
          amount?: string;
          memo?: string;
          fitid?: string | null;
          dedup_key?: string;
          status?: "pendente" | "conciliada" | "criada" | "ignorada";
          matched_transaction_id?: string | null;
          matched_at?: string | null;
          matched_by?: string | null;
          created_at?: string;
          ignored_reason?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "statement_lines_bank_account_fk";
            columns: ["bank_account_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "bank_accounts";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "statement_lines_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "statement_lines_import_id_fkey";
            columns: ["import_id"];
            isOneToOne: false;
            referencedRelation: "statement_imports";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "statement_lines_matched_by_fkey";
            columns: ["matched_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "statement_lines_matched_transaction_id_fkey";
            columns: ["matched_transaction_id"];
            isOneToOne: false;
            referencedRelation: "transactions";
            referencedColumns: ["id"];
          },
        ];
      };
      transactions: {
        Row: {
          id: string;
          company_id: string;
          bank_account_id: string;
          category_id: string | null;
          counterparty_id: string | null;
          cost_center_id: string | null;
          booking_date: string;
          competence_date: string;
          amount: string;
          direction: "entrada" | "saida" | null;
          status: "previsto" | "realizado";
          reconciliation: "nao_conciliado" | "conciliado" | "ignorado";
          payment_method:
            | "pix"
            | "ted"
            | "doc"
            | "boleto"
            | "debito_automatico"
            | "cartao"
            | "dinheiro"
            | "cheque"
            | "outro"
            | null;
          description: string;
          document_number: string | null;
          notes: string | null;
          transfer_group_id: string | null;
          is_transfer: boolean | null;
          recurrence_id: string | null;
          settles_transaction_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          bank_account_id: string;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          booking_date: string;
          competence_date: string;
          amount: string;
          status?: "previsto" | "realizado";
          reconciliation?: "nao_conciliado" | "conciliado" | "ignorado";
          payment_method?:
            | "pix"
            | "ted"
            | "doc"
            | "boleto"
            | "debito_automatico"
            | "cartao"
            | "dinheiro"
            | "cheque"
            | "outro"
            | null;
          description: string;
          document_number?: string | null;
          notes?: string | null;
          transfer_group_id?: string | null;
          recurrence_id?: string | null;
          settles_transaction_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          bank_account_id?: string;
          category_id?: string | null;
          counterparty_id?: string | null;
          cost_center_id?: string | null;
          booking_date?: string;
          competence_date?: string;
          amount?: string;
          status?: "previsto" | "realizado";
          reconciliation?: "nao_conciliado" | "conciliado" | "ignorado";
          payment_method?:
            | "pix"
            | "ted"
            | "doc"
            | "boleto"
            | "debito_automatico"
            | "cartao"
            | "dinheiro"
            | "cheque"
            | "outro"
            | null;
          description?: string;
          document_number?: string | null;
          notes?: string | null;
          transfer_group_id?: string | null;
          recurrence_id?: string | null;
          settles_transaction_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "transactions_bank_account_fk";
            columns: ["bank_account_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "bank_accounts";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "transactions_category_fk";
            columns: ["category_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "transactions_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "transactions_cost_center_fk";
            columns: ["cost_center_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "cost_centers";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "transactions_counterparty_fk";
            columns: ["counterparty_id", "company_id"];
            isOneToOne: false;
            referencedRelation: "counterparties";
            referencedColumns: ["id", "company_id"];
          },
          {
            foreignKeyName: "transactions_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "transactions_recurrence_fk";
            columns: ["recurrence_id"];
            isOneToOne: false;
            referencedRelation: "recurrences";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "transactions_settles_transaction_id_fkey";
            columns: ["settles_transaction_id"];
            isOneToOne: false;
            referencedRelation: "transactions";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      v_account_balances: {
        Row: {
          bank_account_id: string | null;
          company_id: string | null;
          name: string | null;
          kind: "corrente" | "poupanca" | "aplicacao" | "cartao_credito" | "caixa" | null;
          bank_name: string | null;
          is_active: boolean | null;
          opening_balance: string | null;
          opening_balance_date: string | null;
          minimum_balance: string | null;
          current_balance: string | null;
          realized_balance: string | null;
          projected_balance: string | null;
          overdue_amount: string | null;
          unreconciled_count: number | null;
        };
        Relationships: [];
      };
      v_account_daily_movement: {
        Row: {
          company_id: string | null;
          bank_account_id: string | null;
          booking_date: string | null;
          status: "previsto" | "realizado" | null;
          net_amount: string | null;
          inflow: string | null;
          outflow: string | null;
          entry_count: number | null;
        };
        Relationships: [];
      };
      v_invoice_balances: {
        Row: {
          invoice_id: string | null;
          company_id: string | null;
          number: string | null;
          series: string | null;
          issued_on: string | null;
          due_on: string | null;
          amount: string | null;
          withheld_amount: string | null;
          client_name: string | null;
          client_tax_id: string | null;
          counterparty_id: string | null;
          status: "aberta" | "recebida_parcial" | "recebida" | "cancelada" | null;
          received_amount: string | null;
          outstanding_amount: string | null;
        };
        Relationships: [];
      };
      v_monthly_category_summary: {
        Row: {
          company_id: string | null;
          period_cash: string | null;
          period_accrual: string | null;
          category_id: string | null;
          category_name: string | null;
          direction: "entrada" | "saida" | null;
          status: "previsto" | "realizado" | null;
          total_amount: string | null;
          entry_count: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      add_member: {
        Args: { p_company_id: string; p_email: string; p_role?: string | null };
        Returns: Database["public"]["Tables"]["memberships"]["Row"];
      };
      close_month: {
        Args: { p_company_id: string; p_period: string; p_notes?: string | null };
        Returns: Database["public"]["Tables"]["monthly_closings"]["Row"];
      };
      create_company: {
        Args: { p_name: string; p_legal_name?: string | null; p_tax_id?: string | null };
        Returns: Database["public"]["Tables"]["companies"]["Row"];
      };
      create_transaction_from_line: {
        Args: {
          p_line_id: string;
          p_category_id?: string | null;
          p_description?: string | null;
          p_rule_id?: string | null;
        };
        Returns: Database["public"]["Tables"]["transactions"]["Row"];
      };
      create_transfer: {
        Args: {
          p_company_id: string;
          p_from_account_id: string;
          p_to_account_id: string;
          p_amount: string;
          p_booking_date: string;
          p_description: string;
          p_notes?: string | null;
        };
        Returns: string;
      };
      ignore_line: {
        Args: { p_line_id: string; p_reason: string };
        Returns: undefined;
      };
      reconcile_line: {
        Args: { p_line_id: string; p_transaction_id: string };
        Returns: undefined;
      };
      reopen_month: {
        Args: { p_company_id: string; p_period: string; p_reason: string };
        Returns: Database["public"]["Tables"]["monthly_closings"]["Row"];
      };
      settle_invoices: {
        Args: { p_transaction_id: string; p_allocations: Json };
        Returns: Database["public"]["Tables"]["invoice_settlements"]["Row"][];
      };
      settle_transaction: {
        Args: {
          p_transaction_id: string;
          p_booking_date?: string | null;
          p_amount?: string | null;
        };
        Returns: Database["public"]["Tables"]["transactions"]["Row"];
      };
      unreconcile_line: {
        Args: { p_line_id: string };
        Returns: undefined;
      };
      unsettle_invoice: {
        Args: { p_settlement_id: string };
        Returns: undefined;
      };
    };
    Enums: {
      bank_account_kind: "corrente" | "poupanca" | "aplicacao" | "cartao_credito" | "caixa";
      category_kind: "entrada" | "saida" | "ambos";
      invoice_status: "aberta" | "recebida_parcial" | "recebida" | "cancelada";
      member_role: "cliente_leitura" | "assistente" | "contador" | "owner";
      payment_method:
        | "pix"
        | "ted"
        | "doc"
        | "boleto"
        | "debito_automatico"
        | "cartao"
        | "dinheiro"
        | "cheque"
        | "outro";
      reconciliation_status: "nao_conciliado" | "conciliado" | "ignorado";
      recurrence_frequency: "mensal" | "semanal" | "quinzenal" | "anual";
      statement_line_status: "pendente" | "conciliada" | "criada" | "ignorada";
      statement_source: "ofx" | "csv" | "manual" | "open_finance" | "pdf";
      transaction_direction: "entrada" | "saida";
      transaction_status: "previsto" | "realizado";
    };
  };
}
